# <img style="float: left; padding-right: 20px; width: 200px" src="https://raw.githubusercontent.com/raxlab/imt2200-data/main/media/logo.jpg">  IMT 2200 - Introducción a Ciencia de Datos
**Pontificia Universidad Católica de Chile**<br>
**Instituto de Ingeniería Matemática y Computacional**<br>
**Semestre 2025-S2**<br>
**Profesor:** Rodrigo A. Carrasco <br>

# <h1><center>Actividad 7 - Actividad de Integración</center></h1>

Esta actividad busca que los estudiantes conecten el trabajo de agrupación y de resumen, junto con calcular estadísticas de datos así como también realizar visualización básica.

## Instrucciones

Este Notebook contiene las instrucciones a realizar para la actividad. 

<b>Al finalizarla, deben subir el Notebook y los archivos generados en un único archivo .zip, al módulo de la Actividad 07 en Canvas.</b>

Para esta actividad trabajarán con el dataset [palmerpenguins](https://github.com/allisonhorst/palmerpenguins/blob/main/README.md), un set de datos con mediciones de 3 especies de pingüinos que habitan en la Antártica y sus islas. Estos datos incluyen peso, tamaño de las aletas y mediciones del "culmen" para hembras y machos de las 3 especies. (Abajo pueden ver una imagen explicativa sobre estas mediciones.)

<img src="culmen_depth.png" alt="bill_size" width="700"/>

## Rúbrica

- Si han logrado todo: 7.0
- Si han logrado sólo los puntos 1 y 2: 5.0
- Menos que eso: 1.0

## 1. Base de datos unificada

### 1.1 Lectura de datos

En la carpeta `penguins/` podrá encontrar tres archivos `.csv`, cada uno con registros de las mediciones de una especie de pingüino antártico.
Primero, lea cada uno de estos archivos como un DataFrame separado.

### 1.2  Base de datos unificada

Ahora junte los tres DataFrames en un nuevo DataFrame llamado `penguins`, agregando una nueva columna `species` que identifique el nombre de la especie de cada pingüino (Adelie, Chinstrap o Gentoo).

### 1.3 Inspección y limpieza

Inspeccione el DataFrame `penguins` y sus columnas. ¿Están correctamente asignados los tipos de cada columna? ¿Alguna podría ser categórica? ¿Existen valores nulos o inválidos? Aplique las transformaciones y limpiezas que considere necesarisas al DataFrame, explicando en los comentarios (o nuevas celdas) por qué hizo dichas transformaciones.

¿Están correctamente asignados los tipos de cada columna? 
>Revise a mano y si
¿Alguna podría ser categórica?
> Si la pregunta se refiere a que si podemos asignarles "categorias", pues si, island y sex son categoricas
¿Existen valores nulos o inválidos?
> Si, en gene

In [1]:
%cd penguins

d:\Curso Python\TrabajosUC\Introducion a Ciencias de Datos\IMT2200-Lucas-Chicao\Actividades\actividad 07\penguins

In [2]:
import pandas as pd

adelie = pd.read_csv("adelie.csv")
chinstrap = pd.read_csv("chinstrap.csv")
gentoo = pd.read_csv("gentoo.csv")

In [117]:
adelie["species"] = "adelie"
chinstrap["species"] = "chinstrap"
gentoo["species"] = "gentoo"

In [119]:
penguins = pd.DataFrame(columns=['island', 'culmen_length_mm', 'culmen_depth_mm', 'flipper_length_mm',
       'body_mass_g', 'sex', "species"])
#penguins = pd.merge(penguins, adelie)

In [120]:
penguins = pd.concat([penguins, adelie, chinstrap, gentoo], axis=0, keys=['island', 'culmen_length_mm', 'culmen_depth_mm', 'flipper_length_mm',
       'body_mass_g', 'sex', "species"])

C:\Users\lmchi\AppData\Local\Temp\ipykernel_1304\374900556.py:1: FutureWarning: The behavior of pd.concat with len(keys) != len(objs) is deprecated. In a future version this will raise instead of truncating to the smaller of the two sequences
  penguins = pd.concat([penguins, adelie, chinstrap, gentoo], axis=0, keys=['island', 'culmen_length_mm', 'culmen_depth_mm', 'flipper_length_mm',
C:\Users\lmchi\AppData\Local\Temp\ipykernel_1304\374900556.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  penguins = pd.concat([penguins, adelie, chinstrap, gentoo], axis=0, keys=['island', 'culmen_length_mm', 'culmen_depth_mm', 'flipper_length_mm',

In [121]:
print(len(adelie))
print(len(chinstrap))
print(len(gentoo))
print(len(penguins))
print(152+68+124)

152
68
124
344
344

In [122]:
penguins.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 344 entries, ('culmen_length_mm', np.int64(0)) to ('flipper_length_mm', np.int64(123))
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   island             344 non-null    object
 1   culmen_length_mm   342 non-null    float64
 2   culmen_depth_mm    342 non-null    float64
 3   flipper_length_mm  342 non-null    float64
 4   body_mass_g        342 non-null    float64
 5   sex                334 non-null    object
 6   species            344 non-null    object
dtypes: float64(4), object(3)
memory usage: 25.3+ KB

In [123]:
for i in penguins["sex"]:
    print(i, type(i))

MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
nan <class 'float'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
nan <class 'float'>
nan <class 'float'>
nan <class 'float'>
nan <class 'float'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
nan <class 'float'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
nan <class 'float'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
nan <class 'float'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
nan <class 'float'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>
. <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
nan <class 'float'>
FEMALE <class 'str'>
MALE <class 'str'>
FEMALE <class 'str'>
MALE <class 'str'>

In [124]:
for i in penguins["island"]:
    print(i, type(i))

Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Torgersen <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Dream <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>
Biscoe <class 'str'>

In [126]:
penguins

                          island  culmen_length_mm  culmen_depth_mm  \
culmen_length_mm  0    Torgersen              39.1             18.7
                  1    Torgersen              39.5             17.4
                  2    Torgersen              40.3             18.0
                  3    Torgersen               NaN              NaN
                  4    Torgersen              36.7             19.3
...                          ...               ...              ...
flipper_length_mm 119     Biscoe               NaN              NaN
                  120     Biscoe              46.8             14.3
                  121     Biscoe              50.4             15.7
                  122     Biscoe              45.2             14.8
                  123     Biscoe              49.9             16.1

                       flipper_length_mm  body_mass_g     sex species
culmen_length_mm  0                181.0       3750.0    MALE  adelie
                  1                186.0       3800.0  FEMALE  adelie
                  2                195.0       3250.0  FEMALE  adelie
                  3                  NaN          NaN     NaN  adelie
                  4                193.0       3450.0  FEMALE  adelie
...                                  ...          ...     ...     ...
flipper_length_mm 119                NaN          NaN     NaN  gentoo
                  120              215.0       4850.0  FEMALE  gentoo
                  121              222.0       5750.0    MALE  gentoo
                  122              212.0       5200.0  FEMALE  gentoo
                  123              213.0       5400.0    MALE  gentoo

[344 rows x 7 columns]

In [127]:
penguins_notnull = penguins.copy()

In [128]:
penguins_notnull = penguins_notnull.dropna(subset=["sex","island"])

In [129]:
penguins.tail()

                       island  culmen_length_mm  culmen_depth_mm  \
flipper_length_mm 119  Biscoe               NaN              NaN
                  120  Biscoe              46.8             14.3
                  121  Biscoe              50.4             15.7
                  122  Biscoe              45.2             14.8
                  123  Biscoe              49.9             16.1

                       flipper_length_mm  body_mass_g     sex species
flipper_length_mm 119                NaN          NaN     NaN  gentoo
                  120              215.0       4850.0  FEMALE  gentoo
                  121              222.0       5750.0    MALE  gentoo
                  122              212.0       5200.0  FEMALE  gentoo
                  123              213.0       5400.0    MALE  gentoo

In [130]:
penguins_notnull.tail()

                       island  culmen_length_mm  culmen_depth_mm  \
flipper_length_mm 118  Biscoe              47.2             13.7
                  120  Biscoe              46.8             14.3
                  121  Biscoe              50.4             15.7
                  122  Biscoe              45.2             14.8
                  123  Biscoe              49.9             16.1

                       flipper_length_mm  body_mass_g     sex species
flipper_length_mm 118              214.0       4925.0  FEMALE  gentoo
                  120              215.0       4850.0  FEMALE  gentoo
                  121              222.0       5750.0    MALE  gentoo
                  122              212.0       5200.0  FEMALE  gentoo
                  123              213.0       5400.0    MALE  gentoo

## 2. Revisión de base de datos

### 2.1 Análisis de base completa

Responda las siguientes preguntas a partir del DataFrame `penguins`:
* a. ¿Cuántas filas tiene la base de datos conjunta?
* b. ¿Cuáles son los valores mínimo y máximo de todas las columnas con datos numéricos?
* c. ¿Cuántos machos y cuántas hembras hay en el set de datos, respectivamente?

### 2.2 Análisis agrupados

Responda las siguientes preguntas:

* a. En promedio, ¿cuál es la especie más pesada de pingüino?
* b. Para cada especie, ¿hay alguna diferencia significativa entre hembras y machos en relación al peso promedio?
* c. ¿En qué especie varía menos el tamaño de aleta?

### 2.1

In [135]:
# a -- Nose porque en el not null aun me considela como filas las que borre xd, aun que si es mas pequeño el dataframe

print(penguins.shape[0])
print(penguins_notnull.shape[0])
print(penguins.size)
print(penguins_notnull.size)

344
334
2408
2338

In [ ]:
# b - No se porque considera adelie como el valor minimo, seguramente por algun tema binario
penguins_notnull.min()

island               Biscoe
culmen_length_mm       32.1
culmen_depth_mm        13.1
flipper_length_mm     172.0
body_mass_g          2700.0
sex                       .
species              adelie
dtype: object

In [ ]:
# b - No se porque considera MALE como el valor maximo, seguramente por algun tema binario
penguins_notnull.max()

island               Torgersen
culmen_length_mm          59.6
culmen_depth_mm           21.5
flipper_length_mm        231.0
body_mass_g             6300.0
sex                       MALE
dtype: object

In [111]:
# c
contador_male = 0
contador_female = 0
for i in penguins_notnull["sex"] :
    if i == "MALE":
        contador_male+=1
    elif  i == "FEMALE":
        contador_female+=1
        
print(contador_male,contador_female)

168 165

### 2.2

In [147]:
# a. En promedio, ¿cuál es la especie más pesada de pingüino?

penguins_adelie = penguins_notnull[penguins_notnull["species"] == "adelie"]
penguins_chinstrap = penguins_notnull[penguins_notnull["species"] == "chinstrap"]
penguins_gentoo = penguins_notnull[penguins_notnull["species"] == "gentoo"]


print(penguins_adelie["body_mass_g"].mean())
print(penguins_chinstrap["body_mass_g"].mean())
print(penguins_gentoo["body_mass_g"].mean())

3706.1643835616437
3733.0882352941176
5090.625

## 3. Análisis exploratorio

### 3.1 Estadísticas de resumen

Elija una de las tres especies y responda las siguientes preguntas solamente para la especie elegida:

* a. ¿Cuál es el coeficiente de correlación entre `culmen_length` y `flipper_length`? ¿Qué nos indica este valor? Comente.
* b. ¿Cual es el peso máximo del percentil 10 (el decil más bajo) para los machos?
* c. ¿Cuál es la varianza de `culmen_depth` para las hembras?

### 3.2 Visualización

Utilizando la librería de visualización de su preferencia (matplotlib, seaborn, plotly), genere los siguientes gráficos:

* a. Un scatterplot que relacione las variables `culmen_length` y `flipper_length` para las tres especies. Utilice colores distintos para diferenciar las especies entre sí.
* b. Un histograma que muestre la distribución de peso para pingüinos macho y hembra. Utilice colores distintos para diferenciar los dos grupos.

Analice y comente los resultados que obtuvo. No olvide colocar título y nombres claros a los ejes de sus gráficos.