In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import zipfile
import os

In [3]:
WHO_life = pd.read_csv('data_2025\\WHO_life_expectancy.csv')
pib2020_2025 = pd.read_csv('data_2025\\pib2020-2025.csv')

In [4]:
WHO_life.columns

Index(['IndicatorCode', 'Indicator', 'ParentLocationCode', 'ParentLocation',
       'Location type', 'SpatialDimValueCode', 'Location', 'Period type',
       'Period', 'Dim1 type', 'Dim1', 'Value'],
      dtype='object')

In [5]:
pib2020_2025.columns

Index(['Country', '2020', '2021', '2022', '2023', '2024', '2025'], dtype='object')

In [7]:
WHO_life['Location']

0                         Lesotho
1        Central African Republic
2                         Lesotho
3                        Eswatini
4                         Somalia
                   ...
24415                 Switzerland
24416                   Australia
24417                      France
24418                   Nicaragua
24419                       Japan
Name: Location, Length: 24420, dtype: object

In [8]:
pib2020_2025['Country']

0      Afghanistan
1          Albania
2          Algeria
3          Andorra
4           Angola
          ...
191        Vietnam
192      Palestine
193          Yemen
194         Zambia
195       Zimbabwe
Name: Country, Length: 196, dtype: object

In [9]:
Wholife_copy = WHO_life.copy()
pib_copy = pib2020_2025.copy()

Wholife_copy = Wholife_copy.rename(columns={'Location':'Country'})

mergeado = pd.merge(Wholife_copy, pib_copy, on= 'Country', how='inner')

In [11]:
mergeado.isnull().sum()

IndicatorCode            0
Indicator                0
ParentLocationCode       0
ParentLocation           0
Location type            0
SpatialDimValueCode      0
Country                  0
Period type              0
Period                   0
Dim1 type                0
Dim1                     0
Value                    0
2020                     0
2021                   132
2022                   132
2023                   132
2024                   264
2025                   660
dtype: int64

In [ ]:
mergeado.duplicated().sum() #No hay nulos

np.int64(0)

In [14]:
mergeado = mergeado.dropna()
mergeado.isnull().sum()

IndicatorCode          0
Indicator              0
ParentLocationCode     0
ParentLocation         0
Location type          0
SpatialDimValueCode    0
Country                0
Period type            0
Period                 0
Dim1 type              0
Dim1                   0
Value                  0
2020                   0
2021                   0
2022                   0
2023                   0
2024                   0
2025                   0
dtype: int64

In [17]:
mergeado.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20592 entries, 0 to 21251
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   IndicatorCode        20592 non-null  object
 1   Indicator            20592 non-null  object
 2   ParentLocationCode   20592 non-null  object
 3   ParentLocation       20592 non-null  object
 4   Location type        20592 non-null  object
 5   SpatialDimValueCode  20592 non-null  object
 6   Country              20592 non-null  object
 7   Period type          20592 non-null  object
 8   Period               20592 non-null  int64
 9   Dim1 type            20592 non-null  object
 10  Dim1                 20592 non-null  object
 11  Value                20592 non-null  object
 12  2020                 20592 non-null  int64
 13  2021                 20592 non-null  float64
 14  2022                 20592 non-null  float64
 15  2023                 20592 non-null  float64
 16  2024                 20592 non-null  float64
 17  2025                 20592 non-null  float64
dtypes: float64(5), int64(2), object(11)
memory usage: 3.0+ MB

In [18]:
mergeado.describe(include='all')

,IndicatorCode,Indicator,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Country,Period type,Period,Dim1 type,Dim1,Value,2020,2021,2022,2023,2024,2025
count,20592,20592,20592,20592,20592,20592,20592,20592,20592.000000,20592,20592,20592,2.059200e+04,2.059200e+04,2.059200e+04,2.059200e+04,2.059200e+04,2.059200e+04
unique,2,2,6,6,1,156,156,1,NaN,1,3,9106,NaN,NaN,NaN,NaN,NaN,NaN
top,WHOSIS_000001,Life expectancy at birth (years),EUR,Europe,Country,LSO,Lesotho,Year,NaN,Sex,Male,21.9 [21.9-22.0],NaN,NaN,NaN,NaN,NaN,NaN
freq,10296,10296,5808,5808,20592,132,132,20592,NaN,20592,6864,30,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010.500000,NaN,NaN,NaN,3.478540e+05,4.003048e+05,4.080724e+05,4.227515e+05,4.342847e+05,4.448719e+05
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.344443,NaN,NaN,NaN,1.349288e+06,1.592312e+06,1.588629e+06,1.602356e+06,1.642742e+06,1.684891e+06
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000.000000,NaN,NaN,NaN,2.220000e+02,2.850000e+02,2.710000e+02,2.890000e+02,3.080000e+02,3.120000e+02
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.000000,NaN,NaN,NaN,1.120175e+04,1.235475e+04,1.361600e+04,1.497475e+04,1.624750e+04,1.692450e+04
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2010.500000,NaN,NaN,NaN,3.686350e+04,4.039550e+04,4.386150e+04,4.507500e+04,4.713550e+04,4.881400e+04
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2016.000000,NaN,NaN,NaN,1.950228e+05,2.204038e+05,2.446150e+05,2.632505e+05,2.680542e+05,2.677322e+05
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2021.000000,NaN,NaN,NaN,1.510336e+07,1.819080e+07,1.830782e+07,1.827035e+07,1.874801e+07,1.923170e+07

In [23]:
mergeado.columns

Index(['IndicatorCode', 'Indicator', 'ParentLocationCode', 'ParentLocation',
       'Location type', 'SpatialDimValueCode', 'Country', 'Period type',
       'Period', 'Dim1 type', 'Dim1', 'Value', '2020', '2021', '2022', '2023',
       '2024', '2025'],
      dtype='object')

In [25]:
mergeado.select_dtypes(include="number").columns

Index(['Period', '2020', '2021', '2022', '2023', '2024', '2025'], dtype='object')

In [26]:
mergeado.select_dtypes(include="object").columns

Index(['IndicatorCode', 'Indicator', 'ParentLocationCode', 'ParentLocation',
       'Location type', 'SpatialDimValueCode', 'Country', 'Period type',
       'Dim1 type', 'Dim1', 'Value'],
      dtype='object')

In [27]:
mergeado['Country'].value_counts()

Country
Lesotho                     132
Central African Republic    132
Eswatini                    132
Somalia                     132
Mozambique                  132
                           ...
Norway                      132
Switzerland                 132
Singapore                   132
Japan                       132
Israel                      132
Name: count, Length: 156, dtype: int64

In [29]:
mergeado['Indicator'].value_counts().head(20)

Indicator
Life expectancy at birth (years)     10296
Life expectancy at age 60 (years)    10296
Name: count, dtype: int64

In [ ]:
mergeado['Value']

0        48.7 [47.8-49.7]
1        49.6 [48.5-50.9]
2        51.5 [50.5-52.6]
3        51.6 [50.7-52.8]
4        51.7 [50.6-53.1]
               ...
21247    24.8 [24.8-24.9]
21248    24.9 [24.8-24.9]
21249    25.3 [25.2-25.3]
21250    25.6 [25.5-25.7]
21251    27.1 [27.0-27.1]
Name: Value, Length: 20592, dtype: object

In [31]:
mergeado['Value'].unique()[:20]

array(['48.7 [47.8-49.7]', '49.6 [48.5-50.9]', '51.5 [50.5-52.6]',
       '51.6 [50.7-52.8]', '51.7 [50.6-53.1]', '52.3 [51.1-53.4]',
       '54.0 [52.9-55.1]', '54.6 [53.3-56.0]', '54.6 [53.5-55.9]',
       '54.8 [53.8-55.8]', '55.4 [54.1-56.6]', '56.1 [55.0-57.2]',
       '56.2 [55.3-57.0]', '56.3 [55.3-57.5]', '56.5 [54.9-58.0]',
       '57.3 [56.5-58.2]', '57.5 [56.3-58.9]', '57.7 [56.6-58.8]',
       '57.8 [56.8-58.9]', '57.9 [56.3-59.7]'], dtype=object)

In [33]:
mergeado['Value_num'] = mergeado['Value'].str.split().str[0].astype(float)
mergeado['Value_num']

0        48.7
1        49.6
2        51.5
3        51.6
4        51.7
         ...
21247    24.8
21248    24.9
21249    25.3
21250    25.6
21251    27.1
Name: Value_num, Length: 20592, dtype: float64

In [36]:
mergeado['Value_num'].isna().sum()

np.int64(0)

In [37]:
mergeado['Value_num'].describe()

count    20592.000000
mean        44.544153
std         26.434586
min          9.100000
25%         18.800000
50%         32.850000
75%         71.700000
max         87.400000
Name: Value_num, dtype: float64

In [38]:
mergeado.groupby('Country')['Value_num'].mean().sort_values().head(10)

Country
Lesotho                     30.143182
Eswatini                    30.397727
Central African Republic    30.425000
Somalia                     32.003788
Zimbabwe                    32.725758
Mozambique                  34.329545
Guinea-Bissau               34.390909
Zambia                      35.018939
Malawi                      35.276515
Sierra Leone                35.429545
Name: Value_num, dtype: float64

In [39]:
mergeado['Indicator'].unique()

array(['Life expectancy at birth (years)',
       'Life expectancy at age 60 (years)'], dtype=object)

In [ ]:
df_birth = mergeado[mergeado['Indicator'] == 'Life expectancy at birth (years)'].copy()

df_60 = mergeado[mergeado['Indicator'] == 'Life expectancy at age 60 (years)'].copy()

array(['Life expectancy at age 60 (years)'], dtype=object)

In [47]:
pivot = mergeado.pivot_table(index='Country',
                             columns='Indicator',
                             values='Value_num',
                             aggfunc='mean')
pivot['Diff_birth_60'] = pivot['Life expectancy at birth (years)'] - pivot['Life expectancy at age 60 (years)']
pivot.sort_values('Diff_birth_60', ascending=False).head()

Indicator,Life expectancy at age 60 (years),Life expectancy at birth (years),Diff_birth_60
Country,,,
Singapore,24.036364,81.671212,57.634848
Iceland,23.906061,81.521212,57.615152
Sweden,23.590909,81.192424,57.601515
Switzerland,24.416667,81.925758,57.509091
Italy,23.953030,81.446970,57.493939

In [49]:
df_birth['Dim1'].value_counts()

Dim1
Male          3432
Both sexes    3432
Female        3432
Name: count, dtype: int64

In [50]:
df_60['Dim1'].value_counts()

Dim1
Male          3432
Both sexes    3432
Female        3432
Name: count, dtype: int64

In [53]:
df_birth.groupby('Dim1')['Value_num'].mean()

Dim1
Both sexes    70.039423
Female        72.477535
Male          67.672407
Name: Value_num, dtype: float64